//------------------------------------------------------------------------------
// <auto-generated>
//     このコードは Resources.resx から手動で同期しています。
//     resx を編集した場合はこのファイルも更新してください (VS 外では自動再生成されません)。
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Codeer.LowCode.Blazor.Extras.Designer.Properties
{
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal Resources()
        {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager(
                        "Codeer.LowCode.Blazor.Extras.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてのリソース検索で現在のスレッドの CurrentUICulture プロパティを
        ///   オーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        private static string GetString(string name)
            => ResourceManager.GetString(name, resourceCulture) ?? string.Empty;

        public static string MappingColumnListHeader => GetString("MappingColumnListHeader");

        public static string MappingAdd => GetString("MappingAdd");

        public static string MappingDelete => GetString("MappingDelete");

        public static string MappingMoveUp => GetString("MappingMoveUp");

        public static string MappingMoveDown => GetString("MappingMoveDown");

        public static string MappingSelectColumnHint => GetString("MappingSelectColumnHint");

        public static string MappingUnnamedColumn => GetString("MappingUnnamedColumn");

        public static string MappingExternalName => GetString("MappingExternalName");

        public static string MappingExternalNameDescription => GetString("MappingExternalNameDescription");

        public static string MappingField => GetString("MappingField");

        public static string MappingFieldDescription => GetString("MappingFieldDescription");

        public static string MappingFixedValue => GetString("MappingFixedValue");

        public static string MappingFixedValueDescription => GetString("MappingFixedValueDescription");

        public static string MappingCodeConversion => GetString("MappingCodeConversion");

        public static string MappingCodeConversionDescription => GetString("MappingCodeConversionDescription");

        public static string MappingConversionModule => GetString("MappingConversionModule");

        public static string MappingConversionExternalField => GetString("MappingConversionExternalField");

        public static string MappingConversionInternalField => GetString("MappingConversionInternalField");

        public static string MappingFixedLength => GetString("MappingFixedLength");

        public static string MappingFixedLengthDescription => GetString("MappingFixedLengthDescription");

        public static string MappingWidth => GetString("MappingWidth");

        public static string MappingAlignment => GetString("MappingAlignment");

        public static string MappingPaddingChar => GetString("MappingPaddingChar");

        public static string SetupMenuApprovalFlow => GetString("SetupMenuApprovalFlow");

        public static string SetupMenuMailHistory => GetString("SetupMenuMailHistory");

        public static string SetupTargetModule => GetString("SetupTargetModule");

        public static string SetupTargetNone => GetString("SetupTargetNone");

        public static string SetupFieldName => GetString("SetupFieldName");

        public static string SetupDbColumn => GetString("SetupDbColumn");

        public static string SetupPrefix => GetString("SetupPrefix");

        public static string SetupDataSource => GetString("SetupDataSource");

        public static string SetupUserModule => GetString("SetupUserModule");

        public static string SetupUserNameField => GetString("SetupUserNameField");

        public static string SetupUserEmailField => GetString("SetupUserEmailField");

        public static string SetupRouteMaster => GetString("SetupRouteMaster");

        public static string SetupRouteStandard => GetString("SetupRouteStandard");


        public static string SetupRouteNone => GetString("SetupRouteNone");

        public static string SetupTurnMail => GetString("SetupTurnMail");

        public static string SetupPageFrame => GetString("SetupPageFrame");

        public static string SetupModuleName => GetString("SetupModuleName");

        public static string SetupResultTitle => GetString("SetupResultTitle");

        public static string SetupDdlHeader => GetString("SetupDdlHeader");

        public static string SetupRun => GetString("SetupRun");

        public static string SetupCopy => GetString("SetupCopy");

        public static string SetupClose => GetString("SetupClose");

        public static string SetupCreatedFormat => GetString("SetupCreatedFormat");

        public static string SetupSkippedFormat => GetString("SetupSkippedFormat");

        public static string SetupParentWiredFormat => GetString("SetupParentWiredFormat");

        public static string SetupReloadNote => GetString("SetupReloadNote");

        public static string SetupDdlDone => GetString("SetupDdlDone");
    }
}
