//------------------------------------------------------------------------------
// <auto-generated>
//     このコードは Resources.resx から手動で同期しています。
//     resx を編集した場合はこのファイルも更新してください (VS 外では自動再生成されません)。
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Codeer.LowCode.Blazor.Extras.Designer.Properties
{
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {
        private static global::System.Resources.ResourceManager? resourceMan;

        private static global::System.Globalization.CultureInfo? resourceCulture;

        internal Resources()
        {
        }

        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    var temp = new global::System.Resources.ResourceManager(
                        "Codeer.LowCode.Blazor.Extras.Designer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   すべてのリソース検索で現在のスレッドの CurrentUICulture プロパティを
        ///   オーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        private static string GetString(string name)
            => ResourceManager.GetString(name, resourceCulture) ?? string.Empty;

        public static string MappingColumnListHeader => GetString("MappingColumnListHeader");

        public static string MappingAdd => GetString("MappingAdd");

        public static string MappingDelete => GetString("MappingDelete");

        public static string MappingMoveUp => GetString("MappingMoveUp");

        public static string MappingMoveDown => GetString("MappingMoveDown");

        public static string MappingSelectColumnHint => GetString("MappingSelectColumnHint");

        public static string MappingUnnamedColumn => GetString("MappingUnnamedColumn");

        public static string MappingExternalName => GetString("MappingExternalName");

        public static string MappingExternalNameDescription => GetString("MappingExternalNameDescription");

        public static string MappingField => GetString("MappingField");

        public static string MappingFieldDescription => GetString("MappingFieldDescription");

        public static string MappingFixedValue => GetString("MappingFixedValue");

        public static string MappingFixedValueDescription => GetString("MappingFixedValueDescription");

        public static string MappingFixedLength => GetString("MappingFixedLength");

        public static string MappingFixedLengthDescription => GetString("MappingFixedLengthDescription");

        public static string MappingWidth => GetString("MappingWidth");

        public static string MappingAlignment => GetString("MappingAlignment");

        public static string MappingPaddingChar => GetString("MappingPaddingChar");

        public static string SetupMenuApprovalFlow => GetString("SetupMenuApprovalFlow");

        public static string SetupDataSource => GetString("SetupDataSource");

        public static string SetupUserModule => GetString("SetupUserModule");

        public static string SetupUserNameField => GetString("SetupUserNameField");

        public static string SetupUserEmailField => GetString("SetupUserEmailField");

        public static string SetupRouteMaster => GetString("SetupRouteMaster");

        public static string SetupRouteStandard => GetString("SetupRouteStandard");

        public static string SetupRouteNone => GetString("SetupRouteNone");

        public static string SetupTurnMail => GetString("SetupTurnMail");

        public static string SetupPageFrame => GetString("SetupPageFrame");

        public static string SetupModuleName => GetString("SetupModuleName");

        public static string SetupResultTitle => GetString("SetupResultTitle");

        public static string SetupDdlHeader => GetString("SetupDdlHeader");

        public static string SetupRun => GetString("SetupRun");

        public static string SetupCopy => GetString("SetupCopy");

        public static string SetupClose => GetString("SetupClose");

        public static string SetupCreatedFormat => GetString("SetupCreatedFormat");

        public static string SetupSkippedFormat => GetString("SetupSkippedFormat");

        public static string SetupReloadNote => GetString("SetupReloadNote");

        public static string SetupDdlDone => GetString("SetupDdlDone");

        public static string SetupMenuMail => GetString("SetupMenuMail");

        public static string SetupMailHistory => GetString("SetupMailHistory");
        public static string SetupMailHistoryDetail => GetString("SetupMailHistoryDetail");

        public static string SetupMenuEditHistory => GetString("SetupMenuEditHistory");

        public static string SetupEditHistoryTargetEnum => GetString("SetupEditHistoryTargetEnum");

        public static string SetupMenuAuditLog => GetString("SetupMenuAuditLog");

        public static string SetupTableName => GetString("SetupTableName");

    
        /// <summary>
        ///   Rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Rows {
            get {
                return ResourceManager.GetString("CrossTabSetting_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Columns {
            get {
                return ResourceManager.GetString("CrossTabSetting_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Measures {
            get {
                return ResourceManager.GetString("CrossTabSetting_Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value filter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Having {
            get {
                return ResourceManager.GetString("CrossTabSetting_Having", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort / Limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Sort {
            get {
                return ResourceManager.GetString("CrossTabSetting_Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Limit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Limit {
            get {
                return ResourceManager.GetString("CrossTabSetting_Limit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Add {
            get {
                return ResourceManager.GetString("CrossTabSetting_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Descending に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Descending {
            get {
                return ResourceManager.GetString("CrossTabSetting_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Field {
            get {
                return ResourceManager.GetString("CrossTabSetting_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Group by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_DateUnit {
            get {
                return ResourceManager.GetString("CrossTabSetting_DateUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Summarize by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Function {
            get {
                return ResourceManager.GetString("CrossTabSetting_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Caption に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Caption {
            get {
                return ResourceManager.GetString("CrossTabSetting_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Target {
            get {
                return ResourceManager.GetString("CrossTabSetting_Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Condition に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Comparison {
            get {
                return ResourceManager.GetString("CrossTabSetting_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_CompareValue {
            get {
                return ResourceManager.GetString("CrossTabSetting_CompareValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort by に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_SortBy {
            get {
                return ResourceManager.GetString("CrossTabSetting_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Order {
            get {
                return ResourceManager.GetString("CrossTabSetting_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Count {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Distinct count に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_CountDistinct {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_CountDistinct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sum に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Sum {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Average に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Avg {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Min {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Max {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (none) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_None {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Year に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Year {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quarter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Quarter {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Month {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Week {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Day {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hour に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Hour {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row / column field に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Group {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Measure {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   = に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_Equal {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≠ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_NotEqual {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &lt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_LessThan {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≤ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_LessThanOrEqual {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_GreaterThan {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ≥ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Enum_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("CrossTabSetting_Enum_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fiscal year start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_FiscalYearStartMonth {
            get {
                return ResourceManager.GetString("CrossTabSetting_FiscalYearStartMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_Format {
            get {
                return ResourceManager.GetString("CrossTabSetting_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Display format (.NET numeric format). Pick from the list or type one such as N1 / P0 / C0. Empty = the field's format. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CrossTabSetting_FormatHint {
            get {
                return ResourceManager.GetString("CrossTabSetting_FormatHint", resourceCulture);
            }
        }
    }
}
