//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.LowCode.Blazor.Extras.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.LowCode.Blazor.Extras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   + Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Dependency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddDependency {
            get {
                return ResourceManager.GetString("AddDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base64 Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Base64Image {
            get {
                return ResourceManager.GetString("Base64Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +{0} more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoreFormat {
            get {
                return ResourceManager.GetString("MoreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }

        internal static string DateFormatDayTitle {
            get {
                return ResourceManager.GetString("DateFormatDayTitle", resourceCulture);
            }
        }

        internal static string DateFormatMonthTitle {
            get {
                return ResourceManager.GetString("DateFormatMonthTitle", resourceCulture);
            }
        }

        internal static string DateFormatDayName {
            get {
                return ResourceManager.GetString("DateFormatDayName", resourceCulture);
            }
        }

        internal static string DateFormatMonthYearShort {
            get {
                return ResourceManager.GetString("DateFormatMonthYearShort", resourceCulture);
            }
        }

        internal static string DateFormatDayGroupShort {
            get {
                return ResourceManager.GetString("DateFormatDayGroupShort", resourceCulture);
            }
        }

        internal static string DateFormatDateShort {
            get {
                return ResourceManager.GetString("DateFormatDateShort", resourceCulture);
            }
        }

        internal static string DateFormatMonthDayShort {
            get {
                return ResourceManager.GetString("DateFormatMonthDayShort", resourceCulture);
            }
        }

        internal static string DateFormatMonthNameFull {
            get {
                return ResourceManager.GetString("DateFormatMonthNameFull", resourceCulture);
            }
        }

        internal static string DateFormatMonthNameShort {
            get {
                return ResourceManager.GetString("DateFormatMonthNameShort", resourceCulture);
            }
        }

        internal static string WeekTitleSameMonth {
            get {
                return ResourceManager.GetString("WeekTitleSameMonth", resourceCulture);
            }
        }

        internal static string WeekTitleDiffMonth {
            get {
                return ResourceManager.GetString("WeekTitleDiffMonth", resourceCulture);
            }
        }

        internal static string RangeTitleFormat {
            get {
                return ResourceManager.GetString("RangeTitleFormat", resourceCulture);
            }
        }
    }
}
