//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.LowCode.Blazor.Extras.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.LowCode.Blazor.Extras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   + Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Dependency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddDependency {
            get {
                return ResourceManager.GetString("AddDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base64 Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Base64Image {
            get {
                return ResourceManager.GetString("Base64Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +{0} more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoreFormat {
            get {
                return ResourceManager.GetString("MoreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }

        internal static string DateFormatDayTitle {
            get {
                return ResourceManager.GetString("DateFormatDayTitle", resourceCulture);
            }
        }

        internal static string DateFormatMonthTitle {
            get {
                return ResourceManager.GetString("DateFormatMonthTitle", resourceCulture);
            }
        }

        internal static string DateFormatDayName {
            get {
                return ResourceManager.GetString("DateFormatDayName", resourceCulture);
            }
        }

        internal static string DateFormatMonthYearShort {
            get {
                return ResourceManager.GetString("DateFormatMonthYearShort", resourceCulture);
            }
        }

        internal static string DateFormatDayGroupShort {
            get {
                return ResourceManager.GetString("DateFormatDayGroupShort", resourceCulture);
            }
        }

        internal static string DateFormatDateShort {
            get {
                return ResourceManager.GetString("DateFormatDateShort", resourceCulture);
            }
        }

        internal static string DateFormatMonthDayShort {
            get {
                return ResourceManager.GetString("DateFormatMonthDayShort", resourceCulture);
            }
        }

        internal static string DateFormatMonthNameFull {
            get {
                return ResourceManager.GetString("DateFormatMonthNameFull", resourceCulture);
            }
        }

        internal static string DateFormatMonthNameShort {
            get {
                return ResourceManager.GetString("DateFormatMonthNameShort", resourceCulture);
            }
        }

        internal static string WeekTitleSameMonth {
            get {
                return ResourceManager.GetString("WeekTitleSameMonth", resourceCulture);
            }
        }

        internal static string WeekTitleDiffMonth {
            get {
                return ResourceManager.GetString("WeekTitleDiffMonth", resourceCulture);
            }
        }

        internal static string RangeTitleFormat {
            get {
                return ResourceManager.GetString("RangeTitleFormat", resourceCulture);
            }
        }

        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }

        internal static string RichTextBold {
            get {
                return ResourceManager.GetString("RichTextBold", resourceCulture);
            }
        }

        internal static string RichTextItalic {
            get {
                return ResourceManager.GetString("RichTextItalic", resourceCulture);
            }
        }

        internal static string RichTextUnderline {
            get {
                return ResourceManager.GetString("RichTextUnderline", resourceCulture);
            }
        }

        internal static string RichTextStrikethrough {
            get {
                return ResourceManager.GetString("RichTextStrikethrough", resourceCulture);
            }
        }

        internal static string RichTextHeading {
            get {
                return ResourceManager.GetString("RichTextHeading", resourceCulture);
            }
        }

        internal static string RichTextNormal {
            get {
                return ResourceManager.GetString("RichTextNormal", resourceCulture);
            }
        }

        internal static string RichTextUnorderedList {
            get {
                return ResourceManager.GetString("RichTextUnorderedList", resourceCulture);
            }
        }

        internal static string RichTextOrderedList {
            get {
                return ResourceManager.GetString("RichTextOrderedList", resourceCulture);
            }
        }

        internal static string RichTextAlignLeft {
            get {
                return ResourceManager.GetString("RichTextAlignLeft", resourceCulture);
            }
        }

        internal static string RichTextAlignCenter {
            get {
                return ResourceManager.GetString("RichTextAlignCenter", resourceCulture);
            }
        }

        internal static string RichTextAlignRight {
            get {
                return ResourceManager.GetString("RichTextAlignRight", resourceCulture);
            }
        }

        internal static string RichTextLink {
            get {
                return ResourceManager.GetString("RichTextLink", resourceCulture);
            }
        }

        internal static string RichTextUndo {
            get {
                return ResourceManager.GetString("RichTextUndo", resourceCulture);
            }
        }

        internal static string RichTextRedo {
            get {
                return ResourceManager.GetString("RichTextRedo", resourceCulture);
            }
        }

        internal static string RichTextForeColor {
            get {
                return ResourceManager.GetString("RichTextForeColor", resourceCulture);
            }
        }

        internal static string RichTextBackColor {
            get {
                return ResourceManager.GetString("RichTextBackColor", resourceCulture);
            }
        }

        internal static string RichTextClearFormat {
            get {
                return ResourceManager.GetString("RichTextClearFormat", resourceCulture);
            }
        }

        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        internal static string SearchCondition {
            get {
                return ResourceManager.GetString("SearchCondition", resourceCulture);
            }
        }

        internal static string CalendarFieldTextField {
            get {
                return ResourceManager.GetString("CalendarFieldTextField", resourceCulture);
            }
        }

        internal static string CalendarFieldStartField {
            get {
                return ResourceManager.GetString("CalendarFieldStartField", resourceCulture);
            }
        }

        internal static string CalendarFieldEndField {
            get {
                return ResourceManager.GetString("CalendarFieldEndField", resourceCulture);
            }
        }

        internal static string CalendarFieldAllDayField {
            get {
                return ResourceManager.GetString("CalendarFieldAllDayField", resourceCulture);
            }
        }

        internal static string CalendarFieldColorField {
            get {
                return ResourceManager.GetString("CalendarFieldColorField", resourceCulture);
            }
        }

        internal static string DetailLayoutName {
            get {
                return ResourceManager.GetString("DetailLayoutName", resourceCulture);
            }
        }

        internal static string CalendarFieldEnableMonthView {
            get {
                return ResourceManager.GetString("CalendarFieldEnableMonthView", resourceCulture);
            }
        }

        internal static string CalendarFieldEnableWeekView {
            get {
                return ResourceManager.GetString("CalendarFieldEnableWeekView", resourceCulture);
            }
        }

        internal static string CalendarFieldEnableDayView {
            get {
                return ResourceManager.GetString("CalendarFieldEnableDayView", resourceCulture);
            }
        }

        internal static string OnDataChanged {
            get {
                return ResourceManager.GetString("OnDataChanged", resourceCulture);
            }
        }

        internal static string GanttFieldTextField {
            get {
                return ResourceManager.GetString("GanttFieldTextField", resourceCulture);
            }
        }

        internal static string GanttFieldStartField {
            get {
                return ResourceManager.GetString("GanttFieldStartField", resourceCulture);
            }
        }

        internal static string GanttFieldEndField {
            get {
                return ResourceManager.GetString("GanttFieldEndField", resourceCulture);
            }
        }

        internal static string GanttFieldProgressField {
            get {
                return ResourceManager.GetString("GanttFieldProgressField", resourceCulture);
            }
        }

        internal static string GanttFieldProgressScale {
            get {
                return ResourceManager.GetString("GanttFieldProgressScale", resourceCulture);
            }
        }

        internal static string GanttFieldIdField {
            get {
                return ResourceManager.GetString("GanttFieldIdField", resourceCulture);
            }
        }

        internal static string GanttFieldProcessingCounterField {
            get {
                return ResourceManager.GetString("GanttFieldProcessingCounterField", resourceCulture);
            }
        }

        internal static string GanttFieldDependenciesModule {
            get {
                return ResourceManager.GetString("GanttFieldDependenciesModule", resourceCulture);
            }
        }

        internal static string GanttFieldDependencySourceIdField {
            get {
                return ResourceManager.GetString("GanttFieldDependencySourceIdField", resourceCulture);
            }
        }

        internal static string GanttFieldDependencyDestinationIdField {
            get {
                return ResourceManager.GetString("GanttFieldDependencyDestinationIdField", resourceCulture);
            }
        }

        internal static string GanttFieldEnableDayView {
            get {
                return ResourceManager.GetString("GanttFieldEnableDayView", resourceCulture);
            }
        }

        internal static string GanttFieldEnableWeekView {
            get {
                return ResourceManager.GetString("GanttFieldEnableWeekView", resourceCulture);
            }
        }

        internal static string GanttFieldEnableMonthView {
            get {
                return ResourceManager.GetString("GanttFieldEnableMonthView", resourceCulture);
            }
        }

        internal static string GanttFieldFitToWidth {
            get {
                return ResourceManager.GetString("GanttFieldFitToWidth", resourceCulture);
            }
        }

        internal static string GanttFieldShowDetailHeader {
            get {
                return ResourceManager.GetString("GanttFieldShowDetailHeader", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRange {
            get {
                return ResourceManager.GetString("GanttFieldCustomRange", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRangeStart {
            get {
                return ResourceManager.GetString("GanttFieldCustomRangeStart", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRangeEnd {
            get {
                return ResourceManager.GetString("GanttFieldCustomRangeEnd", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRangeEditable {
            get {
                return ResourceManager.GetString("GanttFieldCustomRangeEditable", resourceCulture);
            }
        }

        internal static string GanttFieldBarColor {
            get {
                return ResourceManager.GetString("GanttFieldBarColor", resourceCulture);
            }
        }

        internal static string GanttFieldBarColorField {
            get {
                return ResourceManager.GetString("GanttFieldBarColorField", resourceCulture);
            }
        }

        internal static string GanttFieldShowToolbar {
            get {
                return ResourceManager.GetString("GanttFieldShowToolbar", resourceCulture);
            }
        }

        internal static string GanttCategoryViewMode {
            get {
                return ResourceManager.GetString("GanttCategoryViewMode", resourceCulture);
            }
        }

        internal static string GanttCategoryDisplay {
            get {
                return ResourceManager.GetString("GanttCategoryDisplay", resourceCulture);
            }
        }

        internal static string GanttCategoryEvents {
            get {
                return ResourceManager.GetString("GanttCategoryEvents", resourceCulture);
            }
        }

        internal static string TaskBoardFieldStatuses {
            get {
                return ResourceManager.GetString("TaskBoardFieldStatuses", resourceCulture);
            }
        }

        internal static string TaskBoardFieldStatusField {
            get {
                return ResourceManager.GetString("TaskBoardFieldStatusField", resourceCulture);
            }
        }

        internal static string TaskBoardFieldSortIndexField {
            get {
                return ResourceManager.GetString("TaskBoardFieldSortIndexField", resourceCulture);
            }
        }

        internal static string TaskBoardFieldCardLayoutName {
            get {
                return ResourceManager.GetString("TaskBoardFieldCardLayoutName", resourceCulture);
            }
        }

        internal static string TaskBoardFieldPopupLayoutName {
            get {
                return ResourceManager.GetString("TaskBoardFieldPopupLayoutName", resourceCulture);
            }
        }

        internal static string TaskBoardFieldEnableDoubleClickPopup {
            get {
                return ResourceManager.GetString("TaskBoardFieldEnableDoubleClickPopup", resourceCulture);
            }
        }

        internal static string RichTextFieldDbColumn {
            get {
                return ResourceManager.GetString("RichTextFieldDbColumn", resourceCulture);
            }
        }

        internal static string ColorPickerFieldDbColumn {
            get {
                return ResourceManager.GetString("ColorPickerFieldDbColumn", resourceCulture);
            }
        }

        internal static string ColorPickerFieldDefault {
            get {
                return ResourceManager.GetString("ColorPickerFieldDefault", resourceCulture);
            }
        }

        internal static string DiscardChangesConfirmation {
            get {
                return ResourceManager.GetString("DiscardChangesConfirmation", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string QrCodeFieldSourceField {
            get {
                return ResourceManager.GetString("QrCodeFieldSourceField", resourceCulture);
            }
        }
        
        internal static string QrCodeFieldText {
            get {
                return ResourceManager.GetString("QrCodeFieldText", resourceCulture);
            }
        }
        
        internal static string QrCodeFieldEccLevel {
            get {
                return ResourceManager.GetString("QrCodeFieldEccLevel", resourceCulture);
            }
        }
        
        internal static string QrCodeFieldDarkColor {
            get {
                return ResourceManager.GetString("QrCodeFieldDarkColor", resourceCulture);
            }
        }
        
        internal static string QrCodeFieldLightColor {
            get {
                return ResourceManager.GetString("QrCodeFieldLightColor", resourceCulture);
            }
        }
        
        internal static string ProgressFieldValueField {
            get {
                return ResourceManager.GetString("ProgressFieldValueField", resourceCulture);
            }
        }

        internal static string ProgressFieldDisplayType {
            get {
                return ResourceManager.GetString("ProgressFieldDisplayType", resourceCulture);
            }
        }

        internal static string ProgressFieldScale {
            get {
                return ResourceManager.GetString("ProgressFieldScale", resourceCulture);
            }
        }

        internal static string ProgressFieldColorField {
            get {
                return ResourceManager.GetString("ProgressFieldColorField", resourceCulture);
            }
        }
        
        internal static string ProgressFieldBarColor {
            get {
                return ResourceManager.GetString("ProgressFieldBarColor", resourceCulture);
            }
        }
        
        internal static string ProgressFieldShowValueLabel {
            get {
                return ResourceManager.GetString("ProgressFieldShowValueLabel", resourceCulture);
            }
        }
        
        internal static string BulkFileTransferButtonSearchFieldName {
            get {
                return ResourceManager.GetString("BulkFileTransferButtonSearchFieldName", resourceCulture);
            }
        }
        
        internal static string BulkFileTransferButtonListFieldName {
            get {
                return ResourceManager.GetString("BulkFileTransferButtonListFieldName", resourceCulture);
            }
        }
        
        internal static string BulkFileTransferButtonOnUploaded {
            get {
                return ResourceManager.GetString("BulkFileTransferButtonOnUploaded", resourceCulture);
            }
        }
        
        internal static string BulkFileTransferButtonSourceCategory {
            get {
                return ResourceManager.GetString("BulkFileTransferButtonSourceCategory", resourceCulture);
            }
        }
        
        internal static string BulkFileTransferButtonConditionSourceInvalid {
            get {
                return ResourceManager.GetString("BulkFileTransferButtonConditionSourceInvalid", resourceCulture);
            }
        }
        
        internal static string SuccessSubmit {
            get {
                return ResourceManager.GetString("SuccessSubmit", resourceCulture);
            }
        }

        
        internal static string ExcelReportButtonTemplateResourcePath {
            get {
                return ResourceManager.GetString("ExcelReportButtonTemplateResourcePath", resourceCulture);
            }
        }
        
        internal static string ExcelReportButtonFormat {
            get {
                return ResourceManager.GetString("ExcelReportButtonFormat", resourceCulture);
            }
        }
        
        internal static string ExcelReportButtonDownloadFileName {
            get {
                return ResourceManager.GetString("ExcelReportButtonDownloadFileName", resourceCulture);
            }
        }
        
        internal static string ExcelReportButtonTemplateRequired {
            get {
                return ResourceManager.GetString("ExcelReportButtonTemplateRequired", resourceCulture);
            }
        }

        
        internal static string AITextAnalyzerField {
            get {
                return ResourceManager.GetString("AITextAnalyzerField", resourceCulture);
            }
        }
        
        internal static string CalendarField {
            get {
                return ResourceManager.GetString("CalendarField", resourceCulture);
            }
        }
        
        internal static string ColorPickerField {
            get {
                return ResourceManager.GetString("ColorPickerField", resourceCulture);
            }
        }
        
        internal static string CsvFileFormatField {
            get {
                return ResourceManager.GetString("CsvFileFormatField", resourceCulture);
            }
        }
        
        internal static string EnterFocusMoveField {
            get {
                return ResourceManager.GetString("EnterFocusMoveField", resourceCulture);
            }
        }
        
        internal static string GanttField {
            get {
                return ResourceManager.GetString("GanttField", resourceCulture);
            }
        }
        
        internal static string FileColumnMappingField {
            get {
                return ResourceManager.GetString("FileColumnMappingField", resourceCulture);
            }
        }
        
        internal static string MarkerListField {
            get {
                return ResourceManager.GetString("MarkerListField", resourceCulture);
            }
        }
        
        internal static string OrientationLockField {
            get {
                return ResourceManager.GetString("OrientationLockField", resourceCulture);
            }
        }
        
        internal static string PasswordHashField {
            get {
                return ResourceManager.GetString("PasswordHashField", resourceCulture);
            }
        }
        
        internal static string ProgressField {
            get {
                return ResourceManager.GetString("ProgressField", resourceCulture);
            }
        }
        
        internal static string QrCodeField {
            get {
                return ResourceManager.GetString("QrCodeField", resourceCulture);
            }
        }
        
        internal static string RichTextField {
            get {
                return ResourceManager.GetString("RichTextField", resourceCulture);
            }
        }
        
        internal static string TaskBoardField {
            get {
                return ResourceManager.GetString("TaskBoardField", resourceCulture);
            }
        }
        
        internal static string BulkFileTransferButtonField {
            get {
                return ResourceManager.GetString("BulkFileTransferButtonField", resourceCulture);
            }
        }
        
        internal static string ExcelReportButtonField {
            get {
                return ResourceManager.GetString("ExcelReportButtonField", resourceCulture);
            }
        }

        internal static string CsvFileFormatEncoding {
            get {
                return ResourceManager.GetString("CsvFileFormatEncoding", resourceCulture);
            }
        }

        internal static string CsvFileFormatDelimiter {
            get {
                return ResourceManager.GetString("CsvFileFormatDelimiter", resourceCulture);
            }
        }

        internal static string CsvFileFormatFileExtension {
            get {
                return ResourceManager.GetString("CsvFileFormatFileExtension", resourceCulture);
            }
        }

        internal static string CsvFileFormatFixedLengthWidthUnit {
            get {
                return ResourceManager.GetString("CsvFileFormatFixedLengthWidthUnit", resourceCulture);
            }
        }

        internal static string FileColumnMappingHasHeader {
            get {
                return ResourceManager.GetString("FileColumnMappingHasHeader", resourceCulture);
            }
        }

        internal static string FileColumnMappingColumns {
            get {
                return ResourceManager.GetString("FileColumnMappingColumns", resourceCulture);
            }
        }

        internal static string CsvFileFormatFixedLengthMappingRequired {
            get {
                return ResourceManager.GetString("CsvFileFormatFixedLengthMappingRequired", resourceCulture);
            }
        }

        internal static string FileColumnMappingFixedLengthWidthRequired {
            get {
                return ResourceManager.GetString("FileColumnMappingFixedLengthWidthRequired", resourceCulture);
            }
        }

        internal static string FileColumnMappingFixedLengthZeroPaddingRequiresRight {
            get {
                return ResourceManager.GetString("FileColumnMappingFixedLengthZeroPaddingRequiresRight", resourceCulture);
            }
        }

        internal static string BulkMailField {
            get {
                return ResourceManager.GetString("BulkMailField", resourceCulture);
            }
        }

        internal static string MailField {
            get {
                return ResourceManager.GetString("MailField", resourceCulture);
            }
        }

        internal static string MailFieldToVariable {
            get {
                return ResourceManager.GetString("MailFieldToVariable", resourceCulture);
            }
        }

        internal static string MailFieldTo {
            get {
                return ResourceManager.GetString("MailFieldTo", resourceCulture);
            }
        }

        internal static string MailFieldCcVariable {
            get {
                return ResourceManager.GetString("MailFieldCcVariable", resourceCulture);
            }
        }

        internal static string MailFieldCc {
            get {
                return ResourceManager.GetString("MailFieldCc", resourceCulture);
            }
        }

        internal static string MailFieldSubjectVariable {
            get {
                return ResourceManager.GetString("MailFieldSubjectVariable", resourceCulture);
            }
        }

        internal static string MailFieldSubject {
            get {
                return ResourceManager.GetString("MailFieldSubject", resourceCulture);
            }
        }

        internal static string MailFieldBodyVariable {
            get {
                return ResourceManager.GetString("MailFieldBodyVariable", resourceCulture);
            }
        }

        internal static string MailFieldBody {
            get {
                return ResourceManager.GetString("MailFieldBody", resourceCulture);
            }
        }

        internal static string MailInfraName {
            get {
                return ResourceManager.GetString("MailInfraName", resourceCulture);
            }
        }

        internal static string MailFieldIsBodyHtml {
            get {
                return ResourceManager.GetString("MailFieldIsBodyHtml", resourceCulture);
            }
        }

        internal static string MailFieldReplyTo {
            get {
                return ResourceManager.GetString("MailFieldReplyTo", resourceCulture);
            }
        }

        internal static string MailFieldFromVariable {
            get {
                return ResourceManager.GetString("MailFieldFromVariable", resourceCulture);
            }
        }

        internal static string MailFieldFromDisplayNameVariable {
            get {
                return ResourceManager.GetString("MailFieldFromDisplayNameVariable", resourceCulture);
            }
        }

        internal static string MailFieldToRequired {
            get {
                return ResourceManager.GetString("MailFieldToRequired", resourceCulture);
            }
        }

        internal static string MailFieldNoRecipient {
            get {
                return ResourceManager.GetString("MailFieldNoRecipient", resourceCulture);
            }
        }


        internal static string MailFieldBccVariable {
            get {
                return ResourceManager.GetString("MailFieldBccVariable", resourceCulture);
            }
        }

        internal static string MailFieldBcc {
            get {
                return ResourceManager.GetString("MailFieldBcc", resourceCulture);
            }
        }

        internal static string MailFieldReplyToVariable {
            get {
                return ResourceManager.GetString("MailFieldReplyToVariable", resourceCulture);
            }
        }

        internal static string MailFieldFrom {
            get {
                return ResourceManager.GetString("MailFieldFrom", resourceCulture);
            }
        }

        internal static string MailFieldFromDisplayName {
            get {
                return ResourceManager.GetString("MailFieldFromDisplayName", resourceCulture);
            }
        }









        internal static string MailFieldSentToast {
            get {
                return ResourceManager.GetString("MailFieldSentToast", resourceCulture);
            }
        }

        internal static string MailFieldSendButtonTitle {
            get {
                return ResourceManager.GetString("MailFieldSendButtonTitle", resourceCulture);
            }
        }

        internal static string MailFieldConfirmSendFormat {
            get {
                return ResourceManager.GetString("MailFieldConfirmSendFormat", resourceCulture);
            }
        }

        internal static string MailFieldSendFailedFormat {
            get {
                return ResourceManager.GetString("MailFieldSendFailedFormat", resourceCulture);
            }
        }

        internal static string MailHistoryContractField {
            get {
                return ResourceManager.GetString("MailHistoryContractField", resourceCulture);
            }
        }




        internal static string BulkMailRecipientContractField {
            get {
                return ResourceManager.GetString("BulkMailRecipientContractField", resourceCulture);
            }
        }

        internal static string ContractCheck_RoleRequiredFormat {
            get {
                return ResourceManager.GetString("ContractCheck_RoleRequiredFormat", resourceCulture);
            }
        }

        internal static string BulkMailRecipientContractEmail {
            get {
                return ResourceManager.GetString("BulkMailRecipientContractEmail", resourceCulture);
            }
        }

        internal static string BulkMailRecipientContractOptOut {
            get {
                return ResourceManager.GetString("BulkMailRecipientContractOptOut", resourceCulture);
            }
        }

        internal static string BulkMailRecipientContractDisplayName {
            get {
                return ResourceManager.GetString("BulkMailRecipientContractDisplayName", resourceCulture);
            }
        }

        internal static string MailFieldPreviewButtonText {
            get {
                return ResourceManager.GetString("MailFieldPreviewButtonText", resourceCulture);
            }
        }

        internal static string MailPreviewFailed {
            get {
                return ResourceManager.GetString("MailPreviewFailed", resourceCulture);
            }
        }

        internal static string MailPreviewSaveBeforePreview {
            get {
                return ResourceManager.GetString("MailPreviewSaveBeforePreview", resourceCulture);
            }
        }

        internal static string MailHistoryContractSentAt {
            get {
                return ResourceManager.GetString("MailHistoryContractSentAt", resourceCulture);
            }
        }

        internal static string MailHistoryContractMailInfraName {
            get {
                return ResourceManager.GetString("MailHistoryContractMailInfraName", resourceCulture);
            }
        }

        internal static string MailHistoryContractSubject {
            get {
                return ResourceManager.GetString("MailHistoryContractSubject", resourceCulture);
            }
        }

        internal static string MailHistoryContractTotalCount {
            get {
                return ResourceManager.GetString("MailHistoryContractTotalCount", resourceCulture);
            }
        }

        internal static string MailHistoryContractSuccessCount {
            get {
                return ResourceManager.GetString("MailHistoryContractSuccessCount", resourceCulture);
            }
        }

        internal static string MailHistoryContractFailureDetails {
            get {
                return ResourceManager.GetString("MailHistoryContractFailureDetails", resourceCulture);
            }
        }

        internal static string MailHistoryContractSourceModule {
            get {
                return ResourceManager.GetString("MailHistoryContractSourceModule", resourceCulture);
            }
        }

        internal static string MailHistoryContractSourceId {
            get {
                return ResourceManager.GetString("MailHistoryContractSourceId", resourceCulture);
            }
        }

        internal static string MailHistoryContractDetails {
            get {
                return ResourceManager.GetString("MailHistoryContractDetails", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractField {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractField", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractHistory {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractHistory", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractTo {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractTo", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractSubject {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractSubject", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractBody {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractBody", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractIsSuccess {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractIsSuccess", resourceCulture);
            }
        }

        internal static string MailHistoryDetailContractError {
            get {
                return ResourceManager.GetString("MailHistoryDetailContractError", resourceCulture);
            }
        }

        internal static string BulkMailRecipientListFieldName {
            get {
                return ResourceManager.GetString("BulkMailRecipientListFieldName", resourceCulture);
            }
        }

        internal static string MailFieldShowPreviewButton {
            get {
                return ResourceManager.GetString("MailFieldShowPreviewButton", resourceCulture);
            }
        }

        internal static string BulkMailRecipientListFieldRequired {
            get {
                return ResourceManager.GetString("BulkMailRecipientListFieldRequired", resourceCulture);
            }
        }

        internal static string MailSubjectOrBodyRequired {
            get {
                return ResourceManager.GetString("MailSubjectOrBodyRequired", resourceCulture);
            }
        }

        internal static string BulkMailSaveBeforeSend {
            get {
                return ResourceManager.GetString("BulkMailSaveBeforeSend", resourceCulture);
            }
        }

        internal static string BulkMailTargetListInvalid {
            get {
                return ResourceManager.GetString("BulkMailTargetListInvalid", resourceCulture);
            }
        }

        internal static string BulkMailConfirmFormat {
            get {
                return ResourceManager.GetString("BulkMailConfirmFormat", resourceCulture);
            }
        }

        internal static string BulkMailSendAction {
            get {
                return ResourceManager.GetString("BulkMailSendAction", resourceCulture);
            }
        }

        internal static string BulkMailSentFormat {
            get {
                return ResourceManager.GetString("BulkMailSentFormat", resourceCulture);
            }
        }

        internal static string BulkMailSentWithFailuresFormat {
            get {
                return ResourceManager.GetString("BulkMailSentWithFailuresFormat", resourceCulture);
            }
        }

        internal static string ApprovalFlowField {
            get {
                return ResourceManager.GetString("ApprovalFlowField", resourceCulture);
            }
        }

        internal static string DbColumn {
            get {
                return ResourceManager.GetString("DbColumn", resourceCulture);
            }
        }

        internal static string ApprovalFlowModuleName {
            get {
                return ResourceManager.GetString("ApprovalFlowModuleName", resourceCulture);
            }
        }

        internal static string ApprovalHistoryField {
            get {
                return ResourceManager.GetString("ApprovalHistoryField", resourceCulture);
            }
        }

        internal static string ApprovalFieldName {
            get {
                return ResourceManager.GetString("ApprovalFieldName", resourceCulture);
            }
        }

        internal static string ApprovalCheck_NotApprovalFlowFieldFormat {
            get {
                return ResourceManager.GetString("ApprovalCheck_NotApprovalFlowFieldFormat", resourceCulture);
            }
        }

        internal static string ApprovalShowProgress {
            get {
                return ResourceManager.GetString("ApprovalShowProgress", resourceCulture);
            }
        }

        internal static string ApprovalShowHistory {
            get {
                return ResourceManager.GetString("ApprovalShowHistory", resourceCulture);
            }
        }

        internal static string ApprovalShowComment {
            get {
                return ResourceManager.GetString("ApprovalShowComment", resourceCulture);
            }
        }

        internal static string ApprovalCheck_RequiredFieldMissingFormat {
            get {
                return ResourceManager.GetString("ApprovalCheck_RequiredFieldMissingFormat", resourceCulture);
            }
        }

        internal static string ApprovalInputInvalid {
            get {
                return ResourceManager.GetString("ApprovalInputInvalid", resourceCulture);
            }
        }

        internal static string ApprovalNotSubmittedText {
            get {
                return ResourceManager.GetString("ApprovalNotSubmittedText", resourceCulture);
            }
        }

        internal static string ApprovalAction_Submit {
            get {
                return ResourceManager.GetString("ApprovalAction_Submit", resourceCulture);
            }
        }

        internal static string ApprovalAction_Approve {
            get {
                return ResourceManager.GetString("ApprovalAction_Approve", resourceCulture);
            }
        }

        internal static string ApprovalAction_Reject {
            get {
                return ResourceManager.GetString("ApprovalAction_Reject", resourceCulture);
            }
        }

        internal static string ApprovalAction_Return {
            get {
                return ResourceManager.GetString("ApprovalAction_Return", resourceCulture);
            }
        }

        internal static string ApprovalAction_Withdraw {
            get {
                return ResourceManager.GetString("ApprovalAction_Withdraw", resourceCulture);
            }
        }


        internal static string ApprovalAction_Resubmit {
            get {
                return ResourceManager.GetString("ApprovalAction_Resubmit", resourceCulture);
            }
        }

        internal static string ApprovalAction_Confirm {
            get {
                return ResourceManager.GetString("ApprovalAction_Confirm", resourceCulture);
            }
        }

        internal static string ApprovalCommentPlaceholder {
            get {
                return ResourceManager.GetString("ApprovalCommentPlaceholder", resourceCulture);
            }
        }

        internal static string ApprovalCommentRequired {
            get {
                return ResourceManager.GetString("ApprovalCommentRequired", resourceCulture);
            }
        }

        internal static string ApprovalDoneFormat {
            get {
                return ResourceManager.GetString("ApprovalDoneFormat", resourceCulture);
            }
        }

        internal static string ApprovalHistoryTitle {
            get {
                return ResourceManager.GetString("ApprovalHistoryTitle", resourceCulture);
            }
        }

        internal static string ApprovalStatus_InProgress {
            get {
                return ResourceManager.GetString("ApprovalStatus_InProgress", resourceCulture);
            }
        }

        internal static string ApprovalStatus_Completed {
            get {
                return ResourceManager.GetString("ApprovalStatus_Completed", resourceCulture);
            }
        }

        internal static string ApprovalStatus_Rejected {
            get {
                return ResourceManager.GetString("ApprovalStatus_Rejected", resourceCulture);
            }
        }

        internal static string ApprovalStatus_Returned {
            get {
                return ResourceManager.GetString("ApprovalStatus_Returned", resourceCulture);
            }
        }

        internal static string ApprovalStatus_Withdrawn {
            get {
                return ResourceManager.GetString("ApprovalStatus_Withdrawn", resourceCulture);
            }
        }


        internal static string ApprovalError_RouteRequired {
            get {
                return ResourceManager.GetString("ApprovalError_RouteRequired", resourceCulture);
            }
        }

        internal static string ApprovalError_InvalidRouteFormat {
            get {
                return ResourceManager.GetString("ApprovalError_InvalidRouteFormat", resourceCulture);
            }
        }

        internal static string ApprovalError_FlowNotFound {
            get {
                return ResourceManager.GetString("ApprovalError_FlowNotFound", resourceCulture);
            }
        }

        internal static string ApprovalError_InvalidState {
            get {
                return ResourceManager.GetString("ApprovalError_InvalidState", resourceCulture);
            }
        }

        internal static string ApprovalError_VersionMismatch {
            get {
                return ResourceManager.GetString("ApprovalError_VersionMismatch", resourceCulture);
            }
        }

        internal static string ApprovalError_NotApprover {
            get {
                return ResourceManager.GetString("ApprovalError_NotApprover", resourceCulture);
            }
        }

        internal static string ApprovalError_NotApplicant {
            get {
                return ResourceManager.GetString("ApprovalError_NotApplicant", resourceCulture);
            }
        }

        internal static string ApprovalError_ReturnNotAllowed {
            get {
                return ResourceManager.GetString("ApprovalError_ReturnNotAllowed", resourceCulture);
            }
        }

        internal static string ApprovalError_AlreadySubmitted {
            get {
                return ResourceManager.GetString("ApprovalError_AlreadySubmitted", resourceCulture);
            }
        }

        internal static string ApprovalError_DesignNotFound {
            get {
                return ResourceManager.GetString("ApprovalError_DesignNotFound", resourceCulture);
            }
        }

        internal static string ApprovalError_TargetSaveFailedFormat {
            get {
                return ResourceManager.GetString("ApprovalError_TargetSaveFailedFormat", resourceCulture);
            }
        }

        internal static string ApprovalError_NoConfirmation {
            get {
                return ResourceManager.GetString("ApprovalError_NoConfirmation", resourceCulture);
            }
        }

        internal static string ApprovalError_WithdrawNotAllowed {
            get {
                return ResourceManager.GetString("ApprovalError_WithdrawNotAllowed", resourceCulture);
            }
        }

        internal static string ApprovalWithdrawPolicy {
            get {
                return ResourceManager.GetString("ApprovalWithdrawPolicy", resourceCulture);
            }
        }

        internal static string ApprovalShowActions {
            get {
                return ResourceManager.GetString("ApprovalShowActions", resourceCulture);
            }
        }

        internal static string ApprovalOnBuildRoute {
            get {
                return ResourceManager.GetString("ApprovalOnBuildRoute", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractField {
            get {
                return ResourceManager.GetString("ApprovalFlowContractField", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractField {
            get {
                return ResourceManager.GetString("ApprovalMemberContractField", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractField {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractField", resourceCulture);
            }
        }







        internal static string ApprovalCheck_ContractFieldMissingFormat {
            get {
                return ResourceManager.GetString("ApprovalCheck_ContractFieldMissingFormat", resourceCulture);
            }
        }

        internal static string ApprovalCheck_ContractFieldDuplicatedFormat {
            get {
                return ResourceManager.GetString("ApprovalCheck_ContractFieldDuplicatedFormat", resourceCulture);
            }
        }

        internal static string ApprovalCheck_RoleMustBeListFormat {
            get {
                return ResourceManager.GetString("ApprovalCheck_RoleMustBeListFormat", resourceCulture);
            }
        }

        internal static string ApprovalCheck_RoleMustBeMailFieldFormat {
            get {
                return ResourceManager.GetString("ApprovalCheck_RoleMustBeMailFieldFormat", resourceCulture);
            }
        }

        internal static string ApprovalFlowStatus_InProgress {
            get {
                return ResourceManager.GetString("ApprovalFlowStatus_InProgress", resourceCulture);
            }
        }

        internal static string ApprovalFlowStatus_Completed {
            get {
                return ResourceManager.GetString("ApprovalFlowStatus_Completed", resourceCulture);
            }
        }

        internal static string ApprovalFlowStatus_Rejected {
            get {
                return ResourceManager.GetString("ApprovalFlowStatus_Rejected", resourceCulture);
            }
        }

        internal static string ApprovalFlowStatus_Returned {
            get {
                return ResourceManager.GetString("ApprovalFlowStatus_Returned", resourceCulture);
            }
        }

        internal static string ApprovalFlowStatus_Withdrawn {
            get {
                return ResourceManager.GetString("ApprovalFlowStatus_Withdrawn", resourceCulture);
            }
        }

        internal static string ApprovalMemberStatus_Pending {
            get {
                return ResourceManager.GetString("ApprovalMemberStatus_Pending", resourceCulture);
            }
        }

        internal static string ApprovalMemberStatus_Waiting {
            get {
                return ResourceManager.GetString("ApprovalMemberStatus_Waiting", resourceCulture);
            }
        }

        internal static string ApprovalMemberStatus_Approved {
            get {
                return ResourceManager.GetString("ApprovalMemberStatus_Approved", resourceCulture);
            }
        }

        internal static string ApprovalMemberStatus_Rejected {
            get {
                return ResourceManager.GetString("ApprovalMemberStatus_Rejected", resourceCulture);
            }
        }

        internal static string ApprovalMemberStatus_Confirmed {
            get {
                return ResourceManager.GetString("ApprovalMemberStatus_Confirmed", resourceCulture);
            }
        }

        internal static string ApprovalMemberStatus_Skipped {
            get {
                return ResourceManager.GetString("ApprovalMemberStatus_Skipped", resourceCulture);
            }
        }

        internal static string ApprovalStepType_Approval {
            get {
                return ResourceManager.GetString("ApprovalStepType_Approval", resourceCulture);
            }
        }

        internal static string ApprovalStepType_Confirmation {
            get {
                return ResourceManager.GetString("ApprovalStepType_Confirmation", resourceCulture);
            }
        }

        internal static string ApprovalCompletionPolicy_RequiredMembers {
            get {
                return ResourceManager.GetString("ApprovalCompletionPolicy_RequiredMembers", resourceCulture);
            }
        }

        internal static string ApprovalCompletionPolicy_All {
            get {
                return ResourceManager.GetString("ApprovalCompletionPolicy_All", resourceCulture);
            }
        }

        internal static string ApprovalCompletionPolicy_Any {
            get {
                return ResourceManager.GetString("ApprovalCompletionPolicy_Any", resourceCulture);
            }
        }

        internal static string ApprovalReturnScope_ApplicantOnly {
            get {
                return ResourceManager.GetString("ApprovalReturnScope_ApplicantOnly", resourceCulture);
            }
        }

        internal static string ApprovalReturnScope_AnyPreviousStep {
            get {
                return ResourceManager.GetString("ApprovalReturnScope_AnyPreviousStep", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractStatus {
            get {
                return ResourceManager.GetString("ApprovalFlowContractStatus", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractTargetModuleName {
            get {
                return ResourceManager.GetString("ApprovalFlowContractTargetModuleName", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractTargetId {
            get {
                return ResourceManager.GetString("ApprovalFlowContractTargetId", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractApplicant {
            get {
                return ResourceManager.GetString("ApprovalFlowContractApplicant", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractAttemptNo {
            get {
                return ResourceManager.GetString("ApprovalFlowContractAttemptNo", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractCurrentStepNo {
            get {
                return ResourceManager.GetString("ApprovalFlowContractCurrentStepNo", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractMembers {
            get {
                return ResourceManager.GetString("ApprovalFlowContractMembers", resourceCulture);
            }
        }

        internal static string ApprovalFlowContractHistories {
            get {
                return ResourceManager.GetString("ApprovalFlowContractHistories", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractFlow {
            get {
                return ResourceManager.GetString("ApprovalMemberContractFlow", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractAttemptNo {
            get {
                return ResourceManager.GetString("ApprovalMemberContractAttemptNo", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractStepNo {
            get {
                return ResourceManager.GetString("ApprovalMemberContractStepNo", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractStepName {
            get {
                return ResourceManager.GetString("ApprovalMemberContractStepName", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractStepType {
            get {
                return ResourceManager.GetString("ApprovalMemberContractStepType", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractCompletionPolicy {
            get {
                return ResourceManager.GetString("ApprovalMemberContractCompletionPolicy", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractIsCommentRequiredOnReject {
            get {
                return ResourceManager.GetString("ApprovalMemberContractIsCommentRequiredOnReject", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractReturnScope {
            get {
                return ResourceManager.GetString("ApprovalMemberContractReturnScope", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractApproverUser {
            get {
                return ResourceManager.GetString("ApprovalMemberContractApproverUser", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractIsRequired {
            get {
                return ResourceManager.GetString("ApprovalMemberContractIsRequired", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractIsFinalStep {
            get {
                return ResourceManager.GetString("ApprovalMemberContractIsFinalStep", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractStatus {
            get {
                return ResourceManager.GetString("ApprovalMemberContractStatus", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractActedAt {
            get {
                return ResourceManager.GetString("ApprovalMemberContractActedAt", resourceCulture);
            }
        }

        internal static string ApprovalMemberContractTurnNotifyMail {
            get {
                return ResourceManager.GetString("ApprovalMemberContractTurnNotifyMail", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractFlow {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractFlow", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractAttemptNo {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractAttemptNo", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractAction {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractAction", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractActorUser {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractActorUser", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractComment {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractComment", resourceCulture);
            }
        }

        internal static string ApprovalHistoryContractActedAt {
            get {
                return ResourceManager.GetString("ApprovalHistoryContractActedAt", resourceCulture);
            }
        }















            internal static string CsvDelimiterKind_Comma {
            get {
                return ResourceManager.GetString("CsvDelimiterKind_Comma", resourceCulture);
            }
        }

        internal static string CsvDelimiterKind_Tab {
            get {
                return ResourceManager.GetString("CsvDelimiterKind_Tab", resourceCulture);
            }
        }

        internal static string CsvDelimiterKind_Semicolon {
            get {
                return ResourceManager.GetString("CsvDelimiterKind_Semicolon", resourceCulture);
            }
        }

        internal static string CsvDelimiterKind_None {
            get {
                return ResourceManager.GetString("CsvDelimiterKind_None", resourceCulture);
            }
        }

        internal static string CsvEncodingKind_Utf8Bom {
            get {
                return ResourceManager.GetString("CsvEncodingKind_Utf8Bom", resourceCulture);
            }
        }

        internal static string CsvEncodingKind_Utf8 {
            get {
                return ResourceManager.GetString("CsvEncodingKind_Utf8", resourceCulture);
            }
        }

        internal static string CsvEncodingKind_ShiftJis {
            get {
                return ResourceManager.GetString("CsvEncodingKind_ShiftJis", resourceCulture);
            }
        }

        internal static string ExcelReportFormat_Xlsx {
            get {
                return ResourceManager.GetString("ExcelReportFormat_Xlsx", resourceCulture);
            }
        }

        internal static string ExcelReportFormat_Pdf {
            get {
                return ResourceManager.GetString("ExcelReportFormat_Pdf", resourceCulture);
            }
        }

        internal static string FixedLengthWidthUnitKind_Byte {
            get {
                return ResourceManager.GetString("FixedLengthWidthUnitKind_Byte", resourceCulture);
            }
        }

        internal static string FixedLengthWidthUnitKind_Char {
            get {
                return ResourceManager.GetString("FixedLengthWidthUnitKind_Char", resourceCulture);
            }
        }

        internal static string FixedLengthAlignmentKind_Left {
            get {
                return ResourceManager.GetString("FixedLengthAlignmentKind_Left", resourceCulture);
            }
        }

        internal static string FixedLengthAlignmentKind_Right {
            get {
                return ResourceManager.GetString("FixedLengthAlignmentKind_Right", resourceCulture);
            }
        }

        internal static string FixedLengthPaddingCharKind_Space {
            get {
                return ResourceManager.GetString("FixedLengthPaddingCharKind_Space", resourceCulture);
            }
        }

        internal static string FixedLengthPaddingCharKind_Zero {
            get {
                return ResourceManager.GetString("FixedLengthPaddingCharKind_Zero", resourceCulture);
            }
        }

        internal static string OrientationKind_Landscape {
            get {
                return ResourceManager.GetString("OrientationKind_Landscape", resourceCulture);
            }
        }

        internal static string OrientationKind_Portrait {
            get {
                return ResourceManager.GetString("OrientationKind_Portrait", resourceCulture);
            }
        }

        internal static string ProgressDisplayType_Bar {
            get {
                return ResourceManager.GetString("ProgressDisplayType_Bar", resourceCulture);
            }
        }

        internal static string ProgressDisplayType_Meter {
            get {
                return ResourceManager.GetString("ProgressDisplayType_Meter", resourceCulture);
            }
        }

        internal static string ProgressScale_Percent {
            get {
                return ResourceManager.GetString("ProgressScale_Percent", resourceCulture);
            }
        }

        internal static string ProgressScale_Ratio {
            get {
                return ResourceManager.GetString("ProgressScale_Ratio", resourceCulture);
            }
        }

        internal static string QrCodeEccLevel_L {
            get {
                return ResourceManager.GetString("QrCodeEccLevel_L", resourceCulture);
            }
        }

        internal static string QrCodeEccLevel_M {
            get {
                return ResourceManager.GetString("QrCodeEccLevel_M", resourceCulture);
            }
        }

        internal static string QrCodeEccLevel_Q {
            get {
                return ResourceManager.GetString("QrCodeEccLevel_Q", resourceCulture);
            }
        }

        internal static string QrCodeEccLevel_H {
            get {
                return ResourceManager.GetString("QrCodeEccLevel_H", resourceCulture);
            }
        }

        internal static string ApprovalWithdrawPolicy_BeforeFirstApproval {
            get {
                return ResourceManager.GetString("ApprovalWithdrawPolicy_BeforeFirstApproval", resourceCulture);
            }
        }

        internal static string ApprovalWithdrawPolicy_Anytime {
            get {
                return ResourceManager.GetString("ApprovalWithdrawPolicy_Anytime", resourceCulture);
            }
        }
















    }
}
