//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.LowCode.Blazor.Extras.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.LowCode.Blazor.Extras.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   + Add に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Dependency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AddDependency {
            get {
                return ResourceManager.GetString("AddDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Base64 Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Base64Image {
            get {
                return ResourceManager.GetString("Base64Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Day に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Delete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fri に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Fri {
            get {
                return ResourceManager.GetString("Fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mon に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Mon {
            get {
                return ResourceManager.GetString("Mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Month に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   +{0} more に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MoreFormat {
            get {
                return ResourceManager.GetString("MoreFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sat {
            get {
                return ResourceManager.GetString("Sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sun に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Sun {
            get {
                return ResourceManager.GetString("Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Task に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Thu {
            get {
                return ResourceManager.GetString("Thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Today に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tue {
            get {
                return ResourceManager.GetString("Tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Wed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Wed {
            get {
                return ResourceManager.GetString("Wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Week に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }

        internal static string DateFormatDayTitle {
            get {
                return ResourceManager.GetString("DateFormatDayTitle", resourceCulture);
            }
        }

        internal static string DateFormatMonthTitle {
            get {
                return ResourceManager.GetString("DateFormatMonthTitle", resourceCulture);
            }
        }

        internal static string DateFormatDayName {
            get {
                return ResourceManager.GetString("DateFormatDayName", resourceCulture);
            }
        }

        internal static string DateFormatMonthYearShort {
            get {
                return ResourceManager.GetString("DateFormatMonthYearShort", resourceCulture);
            }
        }

        internal static string DateFormatDayGroupShort {
            get {
                return ResourceManager.GetString("DateFormatDayGroupShort", resourceCulture);
            }
        }

        internal static string DateFormatDateShort {
            get {
                return ResourceManager.GetString("DateFormatDateShort", resourceCulture);
            }
        }

        internal static string DateFormatMonthDayShort {
            get {
                return ResourceManager.GetString("DateFormatMonthDayShort", resourceCulture);
            }
        }

        internal static string DateFormatMonthNameFull {
            get {
                return ResourceManager.GetString("DateFormatMonthNameFull", resourceCulture);
            }
        }

        internal static string DateFormatMonthNameShort {
            get {
                return ResourceManager.GetString("DateFormatMonthNameShort", resourceCulture);
            }
        }

        internal static string WeekTitleSameMonth {
            get {
                return ResourceManager.GetString("WeekTitleSameMonth", resourceCulture);
            }
        }

        internal static string WeekTitleDiffMonth {
            get {
                return ResourceManager.GetString("WeekTitleDiffMonth", resourceCulture);
            }
        }

        internal static string RangeTitleFormat {
            get {
                return ResourceManager.GetString("RangeTitleFormat", resourceCulture);
            }
        }

        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }

        internal static string RichTextBold {
            get {
                return ResourceManager.GetString("RichTextBold", resourceCulture);
            }
        }

        internal static string RichTextItalic {
            get {
                return ResourceManager.GetString("RichTextItalic", resourceCulture);
            }
        }

        internal static string RichTextUnderline {
            get {
                return ResourceManager.GetString("RichTextUnderline", resourceCulture);
            }
        }

        internal static string RichTextStrikethrough {
            get {
                return ResourceManager.GetString("RichTextStrikethrough", resourceCulture);
            }
        }

        internal static string RichTextHeading {
            get {
                return ResourceManager.GetString("RichTextHeading", resourceCulture);
            }
        }

        internal static string RichTextNormal {
            get {
                return ResourceManager.GetString("RichTextNormal", resourceCulture);
            }
        }

        internal static string RichTextUnorderedList {
            get {
                return ResourceManager.GetString("RichTextUnorderedList", resourceCulture);
            }
        }

        internal static string RichTextOrderedList {
            get {
                return ResourceManager.GetString("RichTextOrderedList", resourceCulture);
            }
        }

        internal static string RichTextAlignLeft {
            get {
                return ResourceManager.GetString("RichTextAlignLeft", resourceCulture);
            }
        }

        internal static string RichTextAlignCenter {
            get {
                return ResourceManager.GetString("RichTextAlignCenter", resourceCulture);
            }
        }

        internal static string RichTextAlignRight {
            get {
                return ResourceManager.GetString("RichTextAlignRight", resourceCulture);
            }
        }

        internal static string RichTextLink {
            get {
                return ResourceManager.GetString("RichTextLink", resourceCulture);
            }
        }

        internal static string RichTextUndo {
            get {
                return ResourceManager.GetString("RichTextUndo", resourceCulture);
            }
        }

        internal static string RichTextRedo {
            get {
                return ResourceManager.GetString("RichTextRedo", resourceCulture);
            }
        }

        internal static string RichTextForeColor {
            get {
                return ResourceManager.GetString("RichTextForeColor", resourceCulture);
            }
        }

        internal static string RichTextBackColor {
            get {
                return ResourceManager.GetString("RichTextBackColor", resourceCulture);
            }
        }

        internal static string RichTextClearFormat {
            get {
                return ResourceManager.GetString("RichTextClearFormat", resourceCulture);
            }
        }

        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }

        internal static string SearchCondition {
            get {
                return ResourceManager.GetString("SearchCondition", resourceCulture);
            }
        }

        internal static string CalendarFieldTextField {
            get {
                return ResourceManager.GetString("CalendarFieldTextField", resourceCulture);
            }
        }

        internal static string CalendarFieldStartField {
            get {
                return ResourceManager.GetString("CalendarFieldStartField", resourceCulture);
            }
        }

        internal static string CalendarFieldEndField {
            get {
                return ResourceManager.GetString("CalendarFieldEndField", resourceCulture);
            }
        }

        internal static string CalendarFieldAllDayField {
            get {
                return ResourceManager.GetString("CalendarFieldAllDayField", resourceCulture);
            }
        }

        internal static string CalendarFieldColorField {
            get {
                return ResourceManager.GetString("CalendarFieldColorField", resourceCulture);
            }
        }

        internal static string DetailLayoutName {
            get {
                return ResourceManager.GetString("DetailLayoutName", resourceCulture);
            }
        }

        internal static string CalendarFieldEnableMonthView {
            get {
                return ResourceManager.GetString("CalendarFieldEnableMonthView", resourceCulture);
            }
        }

        internal static string CalendarFieldEnableWeekView {
            get {
                return ResourceManager.GetString("CalendarFieldEnableWeekView", resourceCulture);
            }
        }

        internal static string CalendarFieldEnableDayView {
            get {
                return ResourceManager.GetString("CalendarFieldEnableDayView", resourceCulture);
            }
        }

        internal static string OnDataChanged {
            get {
                return ResourceManager.GetString("OnDataChanged", resourceCulture);
            }
        }

        internal static string GanttFieldTextField {
            get {
                return ResourceManager.GetString("GanttFieldTextField", resourceCulture);
            }
        }

        internal static string GanttFieldStartField {
            get {
                return ResourceManager.GetString("GanttFieldStartField", resourceCulture);
            }
        }

        internal static string GanttFieldEndField {
            get {
                return ResourceManager.GetString("GanttFieldEndField", resourceCulture);
            }
        }

        internal static string GanttFieldProgressField {
            get {
                return ResourceManager.GetString("GanttFieldProgressField", resourceCulture);
            }
        }

        internal static string GanttFieldIdField {
            get {
                return ResourceManager.GetString("GanttFieldIdField", resourceCulture);
            }
        }

        internal static string GanttFieldProcessingCounterField {
            get {
                return ResourceManager.GetString("GanttFieldProcessingCounterField", resourceCulture);
            }
        }

        internal static string GanttFieldDependenciesModule {
            get {
                return ResourceManager.GetString("GanttFieldDependenciesModule", resourceCulture);
            }
        }

        internal static string GanttFieldDependencySourceIdField {
            get {
                return ResourceManager.GetString("GanttFieldDependencySourceIdField", resourceCulture);
            }
        }

        internal static string GanttFieldDependencyDestinationIdField {
            get {
                return ResourceManager.GetString("GanttFieldDependencyDestinationIdField", resourceCulture);
            }
        }

        internal static string GanttFieldEnableDayView {
            get {
                return ResourceManager.GetString("GanttFieldEnableDayView", resourceCulture);
            }
        }

        internal static string GanttFieldEnableWeekView {
            get {
                return ResourceManager.GetString("GanttFieldEnableWeekView", resourceCulture);
            }
        }

        internal static string GanttFieldEnableMonthView {
            get {
                return ResourceManager.GetString("GanttFieldEnableMonthView", resourceCulture);
            }
        }

        internal static string GanttFieldFitToWidth {
            get {
                return ResourceManager.GetString("GanttFieldFitToWidth", resourceCulture);
            }
        }

        internal static string GanttFieldShowDetailHeader {
            get {
                return ResourceManager.GetString("GanttFieldShowDetailHeader", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRange {
            get {
                return ResourceManager.GetString("GanttFieldCustomRange", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRangeStart {
            get {
                return ResourceManager.GetString("GanttFieldCustomRangeStart", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRangeEnd {
            get {
                return ResourceManager.GetString("GanttFieldCustomRangeEnd", resourceCulture);
            }
        }

        internal static string GanttFieldCustomRangeEditable {
            get {
                return ResourceManager.GetString("GanttFieldCustomRangeEditable", resourceCulture);
            }
        }

        internal static string GanttFieldShowToolbar {
            get {
                return ResourceManager.GetString("GanttFieldShowToolbar", resourceCulture);
            }
        }

        internal static string GanttCategoryViewMode {
            get {
                return ResourceManager.GetString("GanttCategoryViewMode", resourceCulture);
            }
        }

        internal static string GanttCategoryDisplay {
            get {
                return ResourceManager.GetString("GanttCategoryDisplay", resourceCulture);
            }
        }

        internal static string GanttCategoryEvents {
            get {
                return ResourceManager.GetString("GanttCategoryEvents", resourceCulture);
            }
        }

        internal static string TaskBoardFieldStatuses {
            get {
                return ResourceManager.GetString("TaskBoardFieldStatuses", resourceCulture);
            }
        }

        internal static string TaskBoardFieldStatusField {
            get {
                return ResourceManager.GetString("TaskBoardFieldStatusField", resourceCulture);
            }
        }

        internal static string TaskBoardFieldSortIndexField {
            get {
                return ResourceManager.GetString("TaskBoardFieldSortIndexField", resourceCulture);
            }
        }

        internal static string TaskBoardFieldCardLayoutName {
            get {
                return ResourceManager.GetString("TaskBoardFieldCardLayoutName", resourceCulture);
            }
        }

        internal static string TaskBoardFieldPopupLayoutName {
            get {
                return ResourceManager.GetString("TaskBoardFieldPopupLayoutName", resourceCulture);
            }
        }

        internal static string TaskBoardFieldEnableDoubleClickPopup {
            get {
                return ResourceManager.GetString("TaskBoardFieldEnableDoubleClickPopup", resourceCulture);
            }
        }

        internal static string RichTextFieldDbColumn {
            get {
                return ResourceManager.GetString("RichTextFieldDbColumn", resourceCulture);
            }
        }

        internal static string DiscardChangesConfirmation {
            get {
                return ResourceManager.GetString("DiscardChangesConfirmation", resourceCulture);
            }
        }

        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

    }
}
