//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codeer.LowCode.Blazor.Extras.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codeer.LowCode.Blazor.Extras.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AI chat agent &apos;{0}&apos; is not registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_AgentNotRegistered {
            get {
                return ResourceManager.GetString("AIChat_AgentNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   no data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_ChartNoData {
            get {
                return ResourceManager.GetString("AIChat_ChartNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No AI chat agent is registered. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_DefaultAgentNotRegistered {
            get {
                return ResourceManager.GetString("AIChat_DefaultAgentNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drawing a chart… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_DrawingChart {
            get {
                return ResourceManager.GetString("AIChat_DrawingChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading the schema… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_ReadingSchema {
            get {
                return ResourceManager.GetString("AIChat_ReadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running a query… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_RunningQuery {
            get {
                return ResourceManager.GetString("AIChat_RunningQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running {0}… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_ToolRunning {
            get {
                return ResourceManager.GetString("AIChat_ToolRunning", resourceCulture);
            }
        }
        /// <summary>
        ///   Reading the design… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_ReadingDesign {
            get {
                return ResourceManager.GetString("AIChat_ReadingDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading a document… に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChat_ReadingDocument {
            get {
                return ResourceManager.GetString("AIChat_ReadingDocument", resourceCulture);
            }
        }

        /// <summary>
        ///   Module &apos;{0}&apos; has no MailField named &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MailField_NotFound {
            get {
                return ResourceManager.GetString("MailField_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Module &apos;{0}&apos; has no BulkMailField named &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string BulkMailField_NotFound {
            get {
                return ResourceManager.GetString("BulkMailField_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Module &apos;{0}&apos; has no AIChatField named &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AIChatField_NotFound {
            get {
                return ResourceManager.GetString("AIChatField_NotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Module &apos;{0}&apos; has no AITextAnalyzerField named &apos;{1}&apos;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AITextAnalyzerField_NotFound {
            get {
                return ResourceManager.GetString("AITextAnalyzerField_NotFound", resourceCulture);
            }
        }
        
    }
}
